name: "Deploy"

on:
  workflow_dispatch:

concurrency:
  group: deploy-to-production
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install dependencies
        run: yarn install

      - name: Generate client bundles
        run: yarn build

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          scp -o StrictHostKeyChecking=no -P "${{ secrets.SSH_PORT }}" -r ${{ github.workspace }}/public "${{ secrets.SERVER_USERNAME }}"@"${{ secrets.SERVER_IP }}":"${{ secrets.REMOTE_PATH }}"
