name: "Deploy"

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: deploy-to-production
  cancel-in-progress: true

jobs:
  check_service_worker:
    runs-on: ubuntu-latest
    name: Check if service-worker is up to date
    steps:
      - name: Run service worker checker job
        uses: ./service-worker-checker

  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest
    environment: production
    needs: check_service_worker
    steps:
      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          scp -o StrictHostKeyChecking=no -v -P "${{ secrets.SSH_PORT }}" -r ${{ github.workspace }}/public "${{ secrets.SERVER_USERNAME }}"@"${{ SERVER_IP }}":/var/www/galata-test/
