name: "Check Service Worker Cache Name"

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  service_worker_checker:
    runs-on: ubuntu-latest
    name: Service Worker Checker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Compare service worker cache name
      uses: galata-dergisi/service-worker-checker@v1.0.1
      with:
        REPO_PATH: ${{ github.workspace }}
