name: "Check Service Worker Cache Name"

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  service_worker_checker:
    runs-on: ubuntu-latest
    name: Service Worker Checker
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14

    - name: Install Yarn
      run: npm install --global yarn

    - run: yarn install
      name: Install dependencies

    - run: yarn build
      name: Generate client bundles

    - name: Compare service worker cache name
      uses: galata-dergisi/service-worker-checker@v1.0.3
      with:
        REPO_PATH: ${{ github.workspace }}
